markdown: redcarpet

redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
